# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main, ci ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: x86_64-linux-gcc
        run: |
          CI_JOB_NAME="x86_64-linux-gcc"
          ARTIFACT_DIR=`pwd`/out
          mkdir build && cd build
          mkdir -p $ARTIFACT_DIR/debug/usr/local
          cmake .. -DTARGET_TRIPLE=x86_64-linux-gcc -DTARGET_ARCH=x64 -DCMAKE_STAGING_PREFIX=$ARTIFACT_DIR/debug/usr/local
          make install -j
          ENGINE_VERSION=`cat engine.version | cut -c1-10`
          PACKAGE_FILE="desktop-x86_64-${ENGINE_VERSION}.beta.debug.tar.gz"
          pushd $ARTIFACT_DIR
          find -type f \( -not -name "MD5SUMS.txt" \) -exec md5sum '{}' \; > MD5SUMS.txt
          cd ..
          tar -czvf $PACKAGE_FILE $ARTIFACT_DIR
          ls -la $PACKAGE_FILE
          md5sum $PACKAGE_FILE > ${PACKAGE_FILE}-MD5SUMS.txt
          ls -la ${PACKAGE_FILE}-MD5SUMS.txt
          popd
          rm -rf $ARTIFACT_DIR
